### ISSUE TITLE
Проблема з контейнером 

### ISSUE THREAD

**Issue by yuandrk** [k3ilona/publisher-slack-bot#29]
При розгортанні контейнера отримуємо помилку, не може знайти файл бінарник 
```
(⎈|k3d-dev:N/A)➜  dev git:(main) docker run -it ghcr.io/k3ilona/ibot:0.0.2-e56bfcd-dev
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./publisher-slack-bot": stat ./publisher-slack-bot: no such file or directory: unknown.
```

@vit-um Напевно він не правильно збирає контейнер,
```
FROM quay.io/projectquay/golang:1.20 as builder
WORKDIR /go/src/app
COPY . .
ARG TARGETARCH
RUN make build TARGETARCH=$TARGETARCH

FROM golang:latest
WORKDIR /
COPY --from=builder /go/src/app/ibot .
COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
ENTRYPOINT ["./publisher-slack-bot", "go"]
```

**Comment by Andygol** [comment]
@yuandrk Яка лінка на образ для розгортання в маніфесті?

Має бути щось типу `oci://ghcr.io/…`

**Comment by vit-um** [comment]
Виправив помилку в докерфайлі, то все через плутанину з назвою бота. Після того як змінив назву більше не перевіряв як збираються зображення.
@yuandrk прошу перевірити, якщо помилок не має, то зроблю наступну артефакт з наступною версію, що працює.

**Comment by yuandrk** [comment]
Бот стартанува, тільки проблема з аутентифікацією, ось лог 

``` 

ilonabot 0.0.3-36441e7-dev started 
socketmode: 2024/01/28 13:16:14 socket_mode_managed_conn.go:293: Starting SocketMode
slack-go/slack2024/01/28 13:16:14 chat.go:228: Sending request: attachments=%5B%7B%22color%22%3A%22%2303574B%22%2C%22fields%22%3A%5B%7B%22title%22%3A%22%D0%92%D0%B5%D1%80%D1%81%D1%96%D1%8F%3A%22%2C%22value%22%3A%220.0.3-36441e7-dev%22%2C%22short%22%3Afalse%7D%5D%2C%22blocks%22%3Anull%7D%5D&channel=&text=%D0%97%D0%B0%D0%BF%D1%83%D1%89%D0%B5%D0%BD%D0%B0+%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0+%D0%B2%D0%B8%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%BD%D1%8F+%D0%B2%D0%B5%D1%80%D1%81%D1%96%D1%97+Slack+%D0%B1%D0%BE%D1%82%D1%83+Ilona&token=
socketmode: 2024/01/28 13:16:14 socket_mode_managed_conn.go:297: Failed to start or connect with SocketMode: not_authed
socketmode: 2024/01/28 13:16:14 socket_mode_managed_conn.go:237: invalid auth when connecting with SocketMode: not_authed
socketmode: 2024/01/28 13:16:14 socket_mode_managed_conn.go:78: Failed to connect with Socket Mode on try 0: not_authed
panic: not_authed
goroutine 1 [running]:
github.com/k3ilona/publisher-slack-bot/cmd.glob..func2(0xbbd1a0?, {0x897e47?, 0x0?, 0x0?})
	/go/src/app/cmd/ilonabot.go:67 +0x516
github.com/spf13/cobra.(*Command).execute(0xbbd1a0, {0xbf20c0, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0xbbcec0)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x425
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/k3ilona/publisher-slack-bot/cmd.Execute()
	/go/src/app/cmd/root.go:25 +0x25
main.main()
	/go/src/app/main.go:11 +0x17
	```
	
Дякую @vit-um
